/*
 * Automatically generated by configure - do not modify
 * Configured with: * './configure' * '--prefix=/var/empty/liburing' * '--includedir=/var/empty/tmp/out/include' * '--mandir=/var/empty/tmp/out/share/man'
 */
#define CONFIG_HAVE_KERNEL_RWF_T
#define CONFIG_HAVE_KERNEL_TIMESPEC
#define CONFIG_HAVE_CXX
#define CONFIG_HAVE_UCONTEXT
#define CONFIG_HAVE_STRINGOP_OVERFLOW
#define CONFIG_HAVE_ARRAY_BOUNDS
